### ISSUE TITLE
Question :)

### ISSUE THREAD

**Issue by edtsech** [Gozala/protocol#2]
This project seems abandoned. Have you came up with the better way to get the same benefits which protocols provide? Just curious.

**Comment by Gozala** [comment]
Yes I guess I could update readme to point to that. I end up settling on something simpler & more javascripty http://github.com/gozala/method

**Comment by edtsech** [comment]
Thanks will take a look!

**Comment by edtsech** [comment]
If it would be mentioned in readme that would be nice, for other guys interested in protocols implementation in JS.
