### ISSUE TITLE
This library is going to go away unless someone steps up

### ISSUE THREAD

**Issue by Gozala** [Gozala/protocol#3]
Hi,

I was approached by @wuhkuh who want's to take over the name `protocol` on npm for a protocol generator/parser package. Given that I am unaware of anyone who may experience issues by doing so I pan on letting @wuhkuh to take over, unless someone steps in by April 3rd, 2017, more specifically: 

1. Provides a reason not to proceed (like doing this would break my lib / app).
2. Will volunteer (presumably same person) to take on maintenance of this library (not replacing with something else).

Regards

**Comment by davidnormo** [comment]
Is there any plan to release this under a different name? I'm interested in using it.

**Comment by Gozala** [comment]
@davidnormo I don't personally have time to maintain this project & there for not interested in publishing it under different name. That being said, I'm happy to let you take over and republish under different name.

**Comment by davidnormo** [comment]
Sure I'd be happy to

**Comment by davidnormo** [comment]
Did you want to transfer this repo over or shall I just fork?
